/// Generated by rustemo. Do not edit manually!
use std::fmt::Debug;
use std::hash::Hash;
use rustemo::{
    Result, Input as InputT, Lexer, Token, TokenRecognizer as TokenRecognizerT, Parser,
    ParserDefinition, State as StateT, Builder,
};
use rustemo::regex::Regex;
use rustemo::once_cell::sync::Lazy;
use rustemo::StringLexer;
use rustemo::LRBuilder;
use super::pg_actions;
use rustemo::{LRParser, LRContext};
use rustemo::Action::{self, Shift, Reduce, Accept};
#[allow(unused_imports)]
use rustemo::debug::{log, logn};
#[allow(unused_imports)]
#[cfg(debug_assertions)]
use rustemo::colored::*;
pub type Input = str;
const STATE_COUNT: usize = 34usize;
const MAX_RECOGNIZERS: usize = 3usize;
#[allow(dead_code)]
const TERMINAL_COUNT: usize = 27usize;
#[allow(clippy::upper_case_acronyms)]
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum TokenKind {
    #[default]
    STOP,
    UNQUOTED_STRING,
    IDENTIFIER,
    SEMICOLON,
    CREATE,
    NODE,
    EDGE,
    GRAPH,
    TYPE,
    OPEN_PAREN,
    CLOSE_PAREN,
    OPEN_ARROW,
    CLOSE_ARROW,
    OPEN_CURLY,
    CLOSE_CURLY,
    COLON,
    COMMA,
    BAR,
    PLUS,
    STAR,
    QUESTION,
    INTEGER_NAME,
    STRING_NAME,
    DATE_NAME,
    NUMBER,
    OPTIONAL,
    QUOTE,
}
use TokenKind as TK;
impl From<TokenKind> for usize {
    fn from(t: TokenKind) -> Self {
        t as usize
    }
}
#[allow(clippy::enum_variant_names)]
#[derive(Clone, Copy, PartialEq)]
pub enum ProdKind {
    PgP1,
    NodesEachOf,
    NodesSingleNode,
    NodeP1,
    IdP1,
    LabelPropertySpecP1,
    LabelSpecOptP1,
    LabelSpecOptP2,
    PropertySpecOptP1,
    PropertySpecOptP2,
    LabelSpecP1,
    PropertySpecP1,
    PropertiesEachOfProperties,
    PropertiesBaseProperty,
    PropertyP1,
    keyP1,
    ValuesEachOfValues,
    ValuesP2,
    SingleValueStringValue,
    SingleValueNumberValue,
}
use ProdKind as PK;
impl std::fmt::Debug for ProdKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            ProdKind::PgP1 => "Pg: Nodes",
            ProdKind::NodesEachOf => "Nodes: Nodes COMMA Nodes",
            ProdKind::NodesSingleNode => "Nodes: Node",
            ProdKind::NodeP1 => "Node: OPEN_PAREN Id LabelPropertySpec CLOSE_PAREN",
            ProdKind::IdP1 => "Id: IDENTIFIER",
            ProdKind::LabelPropertySpecP1 => {
                "LabelPropertySpec: LabelSpecOpt PropertySpecOpt"
            }
            ProdKind::LabelSpecOptP1 => "LabelSpecOpt: LabelSpec",
            ProdKind::LabelSpecOptP2 => "LabelSpecOpt: ",
            ProdKind::PropertySpecOptP1 => "PropertySpecOpt: PropertySpec",
            ProdKind::PropertySpecOptP2 => "PropertySpecOpt: ",
            ProdKind::LabelSpecP1 => "LabelSpec: COLON IDENTIFIER",
            ProdKind::PropertySpecP1 => "PropertySpec: OPEN_CURLY Properties CLOSE_CURLY",
            ProdKind::PropertiesEachOfProperties => {
                "Properties: Properties COMMA Properties"
            }
            ProdKind::PropertiesBaseProperty => "Properties: Property",
            ProdKind::PropertyP1 => "Property: key COLON Values",
            ProdKind::keyP1 => "key: IDENTIFIER",
            ProdKind::ValuesEachOfValues => "Values: Values COMMA Values",
            ProdKind::ValuesP2 => "Values: SingleValue",
            ProdKind::SingleValueStringValue => {
                "SingleValue: QUOTE UNQUOTED_STRING QUOTE"
            }
            ProdKind::SingleValueNumberValue => "SingleValue: NUMBER",
        };
        write!(f, "{name}")
    }
}
#[allow(clippy::upper_case_acronyms)]
#[allow(dead_code)]
#[derive(Clone, Copy, Debug)]
pub enum NonTermKind {
    EMPTY,
    AUG,
    Pg,
    Nodes,
    Node,
    Id,
    LabelPropertySpec,
    LabelSpecOpt,
    PropertySpecOpt,
    LabelSpec,
    PropertySpec,
    Properties,
    Property,
    key,
    Values,
    SingleValue,
}
impl From<ProdKind> for NonTermKind {
    fn from(prod: ProdKind) -> Self {
        match prod {
            ProdKind::PgP1 => NonTermKind::Pg,
            ProdKind::NodesEachOf => NonTermKind::Nodes,
            ProdKind::NodesSingleNode => NonTermKind::Nodes,
            ProdKind::NodeP1 => NonTermKind::Node,
            ProdKind::IdP1 => NonTermKind::Id,
            ProdKind::LabelPropertySpecP1 => NonTermKind::LabelPropertySpec,
            ProdKind::LabelSpecOptP1 => NonTermKind::LabelSpecOpt,
            ProdKind::LabelSpecOptP2 => NonTermKind::LabelSpecOpt,
            ProdKind::PropertySpecOptP1 => NonTermKind::PropertySpecOpt,
            ProdKind::PropertySpecOptP2 => NonTermKind::PropertySpecOpt,
            ProdKind::LabelSpecP1 => NonTermKind::LabelSpec,
            ProdKind::PropertySpecP1 => NonTermKind::PropertySpec,
            ProdKind::PropertiesEachOfProperties => NonTermKind::Properties,
            ProdKind::PropertiesBaseProperty => NonTermKind::Properties,
            ProdKind::PropertyP1 => NonTermKind::Property,
            ProdKind::keyP1 => NonTermKind::key,
            ProdKind::ValuesEachOfValues => NonTermKind::Values,
            ProdKind::ValuesP2 => NonTermKind::Values,
            ProdKind::SingleValueStringValue => NonTermKind::SingleValue,
            ProdKind::SingleValueNumberValue => NonTermKind::SingleValue,
        }
    }
}
#[allow(clippy::enum_variant_names)]
#[derive(Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum State {
    #[default]
    AUGS0,
    OPEN_PARENS1,
    PgS2,
    NodesS3,
    NodeS4,
    IDENTIFIERS5,
    IdS6,
    COMMAS7,
    COLONS8,
    LabelPropertySpecS9,
    LabelSpecOptS10,
    LabelSpecS11,
    NodesS12,
    IDENTIFIERS13,
    CLOSE_PARENS14,
    OPEN_CURLYS15,
    PropertySpecOptS16,
    PropertySpecS17,
    IDENTIFIERS18,
    PropertiesS19,
    PropertyS20,
    keyS21,
    CLOSE_CURLYS22,
    COMMAS23,
    COLONS24,
    PropertiesS25,
    NUMBERS26,
    QUOTES27,
    ValuesS28,
    SingleValueS29,
    UNQUOTED_STRINGS30,
    COMMAS31,
    QUOTES32,
    ValuesS33,
}
impl StateT for State {
    fn default_layout() -> Option<Self> {
        None
    }
}
impl From<State> for usize {
    fn from(s: State) -> Self {
        s as usize
    }
}
impl std::fmt::Debug for State {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let name = match self {
            State::AUGS0 => "0:AUG",
            State::OPEN_PARENS1 => "1:OPEN_PAREN",
            State::PgS2 => "2:Pg",
            State::NodesS3 => "3:Nodes",
            State::NodeS4 => "4:Node",
            State::IDENTIFIERS5 => "5:IDENTIFIER",
            State::IdS6 => "6:Id",
            State::COMMAS7 => "7:COMMA",
            State::COLONS8 => "8:COLON",
            State::LabelPropertySpecS9 => "9:LabelPropertySpec",
            State::LabelSpecOptS10 => "10:LabelSpecOpt",
            State::LabelSpecS11 => "11:LabelSpec",
            State::NodesS12 => "12:Nodes",
            State::IDENTIFIERS13 => "13:IDENTIFIER",
            State::CLOSE_PARENS14 => "14:CLOSE_PAREN",
            State::OPEN_CURLYS15 => "15:OPEN_CURLY",
            State::PropertySpecOptS16 => "16:PropertySpecOpt",
            State::PropertySpecS17 => "17:PropertySpec",
            State::IDENTIFIERS18 => "18:IDENTIFIER",
            State::PropertiesS19 => "19:Properties",
            State::PropertyS20 => "20:Property",
            State::keyS21 => "21:key",
            State::CLOSE_CURLYS22 => "22:CLOSE_CURLY",
            State::COMMAS23 => "23:COMMA",
            State::COLONS24 => "24:COLON",
            State::PropertiesS25 => "25:Properties",
            State::NUMBERS26 => "26:NUMBER",
            State::QUOTES27 => "27:QUOTE",
            State::ValuesS28 => "28:Values",
            State::SingleValueS29 => "29:SingleValue",
            State::UNQUOTED_STRINGS30 => "30:UNQUOTED_STRING",
            State::COMMAS31 => "31:COMMA",
            State::QUOTES32 => "32:QUOTE",
            State::ValuesS33 => "33:Values",
        };
        write!(f, "{name}")
    }
}
#[derive(Debug)]
pub enum Symbol {
    Terminal(Terminal),
    NonTerminal(NonTerminal),
}
#[allow(clippy::upper_case_acronyms)]
#[derive(Debug)]
pub enum Terminal {
    UNQUOTED_STRING(pg_actions::UNQUOTED_STRING),
    IDENTIFIER(pg_actions::IDENTIFIER),
    OPEN_PAREN,
    CLOSE_PAREN,
    OPEN_CURLY,
    CLOSE_CURLY,
    COLON,
    COMMA,
    NUMBER(pg_actions::NUMBER),
    QUOTE,
}
#[derive(Debug)]
pub enum NonTerminal {
    Pg(pg_actions::Pg),
    Nodes(pg_actions::Nodes),
    Node(pg_actions::Node),
    Id(pg_actions::Id),
    LabelPropertySpec(pg_actions::LabelPropertySpec),
    LabelSpecOpt(pg_actions::LabelSpecOpt),
    PropertySpecOpt(pg_actions::PropertySpecOpt),
    LabelSpec(pg_actions::LabelSpec),
    PropertySpec(pg_actions::PropertySpec),
    Properties(pg_actions::Properties),
    Property(pg_actions::Property),
    key(pg_actions::key),
    Values(pg_actions::Values),
    SingleValue(pg_actions::SingleValue),
}
type ActionFn = fn(token: TokenKind) -> Vec<Action<State, ProdKind>>;
pub struct PgParserDefinition {
    actions: [ActionFn; STATE_COUNT],
    gotos: [fn(nonterm: NonTermKind) -> State; STATE_COUNT],
    token_kinds: [[Option<(TokenKind, bool)>; MAX_RECOGNIZERS]; STATE_COUNT],
}
fn action_aug_s0(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::OPEN_PAREN => Vec::from(&[Shift(State::OPEN_PARENS1)]),
        _ => vec![],
    }
}
fn action_open_paren_s1(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::IDENTIFIER => Vec::from(&[Shift(State::IDENTIFIERS5)]),
        _ => vec![],
    }
}
fn action_pg_s2(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::STOP => Vec::from(&[Accept]),
        _ => vec![],
    }
}
fn action_nodes_s3(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::STOP => Vec::from(&[Reduce(PK::PgP1, 1usize)]),
        TK::COMMA => Vec::from(&[Shift(State::COMMAS7)]),
        _ => vec![],
    }
}
fn action_node_s4(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::STOP => Vec::from(&[Reduce(PK::NodesSingleNode, 1usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::NodesSingleNode, 1usize)]),
        _ => vec![],
    }
}
fn action_identifier_s5(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::IdP1, 1usize)]),
        TK::OPEN_CURLY => Vec::from(&[Reduce(PK::IdP1, 1usize)]),
        TK::COLON => Vec::from(&[Reduce(PK::IdP1, 1usize)]),
        _ => vec![],
    }
}
fn action_id_s6(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::LabelSpecOptP2, 0usize)]),
        TK::OPEN_CURLY => Vec::from(&[Reduce(PK::LabelSpecOptP2, 0usize)]),
        TK::COLON => Vec::from(&[Shift(State::COLONS8)]),
        _ => vec![],
    }
}
fn action_comma_s7(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::OPEN_PAREN => Vec::from(&[Shift(State::OPEN_PARENS1)]),
        _ => vec![],
    }
}
fn action_colon_s8(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::IDENTIFIER => Vec::from(&[Shift(State::IDENTIFIERS13)]),
        _ => vec![],
    }
}
fn action_labelpropertyspec_s9(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Shift(State::CLOSE_PARENS14)]),
        _ => vec![],
    }
}
fn action_labelspecopt_s10(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::PropertySpecOptP2, 0usize)]),
        TK::OPEN_CURLY => Vec::from(&[Shift(State::OPEN_CURLYS15)]),
        _ => vec![],
    }
}
fn action_labelspec_s11(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::LabelSpecOptP1, 1usize)]),
        TK::OPEN_CURLY => Vec::from(&[Reduce(PK::LabelSpecOptP1, 1usize)]),
        _ => vec![],
    }
}
fn action_nodes_s12(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::STOP => Vec::from(&[Reduce(PK::NodesEachOf, 3usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::NodesEachOf, 3usize)]),
        _ => vec![],
    }
}
fn action_identifier_s13(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::LabelSpecP1, 2usize)]),
        TK::OPEN_CURLY => Vec::from(&[Reduce(PK::LabelSpecP1, 2usize)]),
        _ => vec![],
    }
}
fn action_close_paren_s14(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::STOP => Vec::from(&[Reduce(PK::NodeP1, 4usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::NodeP1, 4usize)]),
        _ => vec![],
    }
}
fn action_open_curly_s15(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::IDENTIFIER => Vec::from(&[Shift(State::IDENTIFIERS18)]),
        _ => vec![],
    }
}
fn action_propertyspecopt_s16(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::LabelPropertySpecP1, 2usize)]),
        _ => vec![],
    }
}
fn action_propertyspec_s17(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::PropertySpecOptP1, 1usize)]),
        _ => vec![],
    }
}
fn action_identifier_s18(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::COLON => Vec::from(&[Reduce(PK::keyP1, 1usize)]),
        _ => vec![],
    }
}
fn action_properties_s19(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Shift(State::CLOSE_CURLYS22)]),
        TK::COMMA => Vec::from(&[Shift(State::COMMAS23)]),
        _ => vec![],
    }
}
fn action_property_s20(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Reduce(PK::PropertiesBaseProperty, 1usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::PropertiesBaseProperty, 1usize)]),
        _ => vec![],
    }
}
fn action_key_s21(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::COLON => Vec::from(&[Shift(State::COLONS24)]),
        _ => vec![],
    }
}
fn action_close_curly_s22(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_PAREN => Vec::from(&[Reduce(PK::PropertySpecP1, 3usize)]),
        _ => vec![],
    }
}
fn action_comma_s23(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::IDENTIFIER => Vec::from(&[Shift(State::IDENTIFIERS18)]),
        _ => vec![],
    }
}
fn action_colon_s24(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::NUMBER => Vec::from(&[Shift(State::NUMBERS26)]),
        TK::QUOTE => Vec::from(&[Shift(State::QUOTES27)]),
        _ => vec![],
    }
}
fn action_properties_s25(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Reduce(PK::PropertiesEachOfProperties, 3usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::PropertiesEachOfProperties, 3usize)]),
        _ => vec![],
    }
}
fn action_number_s26(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Reduce(PK::SingleValueNumberValue, 1usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::SingleValueNumberValue, 1usize)]),
        _ => vec![],
    }
}
fn action_quote_s27(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::UNQUOTED_STRING => Vec::from(&[Shift(State::UNQUOTED_STRINGS30)]),
        _ => vec![],
    }
}
fn action_values_s28(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Reduce(PK::PropertyP1, 3usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::PropertyP1, 3usize)]),
        _ => vec![],
    }
}
fn action_singlevalue_s29(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Reduce(PK::ValuesP2, 1usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::ValuesP2, 1usize)]),
        _ => vec![],
    }
}
fn action_unquoted_string_s30(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::QUOTE => Vec::from(&[Shift(State::QUOTES32)]),
        _ => vec![],
    }
}
fn action_comma_s31(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::NUMBER => Vec::from(&[Shift(State::NUMBERS26)]),
        TK::QUOTE => Vec::from(&[Shift(State::QUOTES27)]),
        _ => vec![],
    }
}
fn action_quote_s32(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Reduce(PK::SingleValueStringValue, 3usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::SingleValueStringValue, 3usize)]),
        _ => vec![],
    }
}
fn action_values_s33(token_kind: TokenKind) -> Vec<Action<State, ProdKind>> {
    match token_kind {
        TK::CLOSE_CURLY => Vec::from(&[Reduce(PK::ValuesEachOfValues, 3usize)]),
        TK::COMMA => Vec::from(&[Reduce(PK::ValuesEachOfValues, 3usize)]),
        _ => vec![],
    }
}
fn goto_aug_s0(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::Pg => State::PgS2,
        NonTermKind::Nodes => State::NodesS3,
        NonTermKind::Node => State::NodeS4,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::AUGS0
            )
        }
    }
}
fn goto_open_paren_s1(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::Id => State::IdS6,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::OPEN_PARENS1
            )
        }
    }
}
fn goto_id_s6(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::LabelPropertySpec => State::LabelPropertySpecS9,
        NonTermKind::LabelSpecOpt => State::LabelSpecOptS10,
        NonTermKind::LabelSpec => State::LabelSpecS11,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::IdS6
            )
        }
    }
}
fn goto_comma_s7(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::Nodes => State::NodesS12,
        NonTermKind::Node => State::NodeS4,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::COMMAS7
            )
        }
    }
}
fn goto_labelspecopt_s10(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::PropertySpecOpt => State::PropertySpecOptS16,
        NonTermKind::PropertySpec => State::PropertySpecS17,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::LabelSpecOptS10
            )
        }
    }
}
fn goto_open_curly_s15(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::Properties => State::PropertiesS19,
        NonTermKind::Property => State::PropertyS20,
        NonTermKind::key => State::keyS21,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::OPEN_CURLYS15
            )
        }
    }
}
fn goto_comma_s23(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::Properties => State::PropertiesS25,
        NonTermKind::Property => State::PropertyS20,
        NonTermKind::key => State::keyS21,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::COMMAS23
            )
        }
    }
}
fn goto_colon_s24(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::Values => State::ValuesS28,
        NonTermKind::SingleValue => State::SingleValueS29,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::COLONS24
            )
        }
    }
}
fn goto_comma_s31(nonterm_kind: NonTermKind) -> State {
    match nonterm_kind {
        NonTermKind::Values => State::ValuesS33,
        NonTermKind::SingleValue => State::SingleValueS29,
        _ => {
            panic!(
                "Invalid terminal kind ({nonterm_kind:?}) for GOTO state ({:?}).",
                State::COMMAS31
            )
        }
    }
}
fn goto_invalid(_nonterm_kind: NonTermKind) -> State {
    panic!("Invalid GOTO entry!");
}
pub(crate) static PARSER_DEFINITION: PgParserDefinition = PgParserDefinition {
    actions: [
        action_aug_s0,
        action_open_paren_s1,
        action_pg_s2,
        action_nodes_s3,
        action_node_s4,
        action_identifier_s5,
        action_id_s6,
        action_comma_s7,
        action_colon_s8,
        action_labelpropertyspec_s9,
        action_labelspecopt_s10,
        action_labelspec_s11,
        action_nodes_s12,
        action_identifier_s13,
        action_close_paren_s14,
        action_open_curly_s15,
        action_propertyspecopt_s16,
        action_propertyspec_s17,
        action_identifier_s18,
        action_properties_s19,
        action_property_s20,
        action_key_s21,
        action_close_curly_s22,
        action_comma_s23,
        action_colon_s24,
        action_properties_s25,
        action_number_s26,
        action_quote_s27,
        action_values_s28,
        action_singlevalue_s29,
        action_unquoted_string_s30,
        action_comma_s31,
        action_quote_s32,
        action_values_s33,
    ],
    gotos: [
        goto_aug_s0,
        goto_open_paren_s1,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_id_s6,
        goto_comma_s7,
        goto_invalid,
        goto_invalid,
        goto_labelspecopt_s10,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_open_curly_s15,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_comma_s23,
        goto_colon_s24,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_invalid,
        goto_comma_s31,
        goto_invalid,
        goto_invalid,
    ],
    token_kinds: [
        [Some((TK::OPEN_PAREN, true)), None, None],
        [Some((TK::IDENTIFIER, false)), None, None],
        [Some((TK::STOP, false)), None, None],
        [Some((TK::STOP, true)), Some((TK::COMMA, true)), None],
        [Some((TK::STOP, true)), Some((TK::COMMA, true)), None],
        [
            Some((TK::CLOSE_PAREN, true)),
            Some((TK::OPEN_CURLY, true)),
            Some((TK::COLON, true)),
        ],
        [
            Some((TK::CLOSE_PAREN, true)),
            Some((TK::OPEN_CURLY, true)),
            Some((TK::COLON, true)),
        ],
        [Some((TK::OPEN_PAREN, true)), None, None],
        [Some((TK::IDENTIFIER, false)), None, None],
        [Some((TK::CLOSE_PAREN, true)), None, None],
        [Some((TK::CLOSE_PAREN, true)), Some((TK::OPEN_CURLY, true)), None],
        [Some((TK::CLOSE_PAREN, true)), Some((TK::OPEN_CURLY, true)), None],
        [Some((TK::STOP, true)), Some((TK::COMMA, true)), None],
        [Some((TK::CLOSE_PAREN, true)), Some((TK::OPEN_CURLY, true)), None],
        [Some((TK::STOP, true)), Some((TK::COMMA, true)), None],
        [Some((TK::IDENTIFIER, false)), None, None],
        [Some((TK::CLOSE_PAREN, true)), None, None],
        [Some((TK::CLOSE_PAREN, true)), None, None],
        [Some((TK::COLON, true)), None, None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
        [Some((TK::COLON, true)), None, None],
        [Some((TK::CLOSE_PAREN, true)), None, None],
        [Some((TK::IDENTIFIER, false)), None, None],
        [Some((TK::QUOTE, true)), Some((TK::NUMBER, false)), None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
        [Some((TK::UNQUOTED_STRING, false)), None, None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
        [Some((TK::QUOTE, true)), None, None],
        [Some((TK::QUOTE, true)), Some((TK::NUMBER, false)), None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
        [Some((TK::CLOSE_CURLY, true)), Some((TK::COMMA, true)), None],
    ],
};
impl ParserDefinition<State, ProdKind, TokenKind, NonTermKind> for PgParserDefinition {
    fn actions(&self, state: State, token: TokenKind) -> Vec<Action<State, ProdKind>> {
        PARSER_DEFINITION.actions[state as usize](token)
    }
    fn goto(&self, state: State, nonterm: NonTermKind) -> State {
        PARSER_DEFINITION.gotos[state as usize](nonterm)
    }
    fn expected_token_kinds(&self, state: State) -> Vec<(TokenKind, bool)> {
        PARSER_DEFINITION.token_kinds[state as usize].iter().map_while(|t| *t).collect()
    }
    fn longest_match() -> bool {
        true
    }
    fn grammar_order() -> bool {
        true
    }
}
pub(crate) type Context<'i, I> = LRContext<'i, I, State, TokenKind>;
pub struct PgParser<
    'i,
    I: InputT + ?Sized,
    L: Lexer<'i, Context<'i, I>, State, TokenKind, Input = I>,
    B,
>(
    LRParser<
        'i,
        Context<'i, I>,
        State,
        ProdKind,
        TokenKind,
        NonTermKind,
        PgParserDefinition,
        L,
        B,
        I,
    >,
);
#[allow(dead_code)]
impl<
    'i,
> PgParser<
    'i,
    Input,
    StringLexer<Context<'i, Input>, State, TokenKind, TokenRecognizer, TERMINAL_COUNT>,
    DefaultBuilder,
> {
    pub fn new() -> Self {
        Self(
            LRParser::new(
                &PARSER_DEFINITION,
                State::default(),
                false,
                false,
                StringLexer::new(true, &RECOGNIZERS),
                DefaultBuilder::new(),
            ),
        )
    }
}
#[allow(dead_code)]
impl<'i, I, L, B> Parser<'i, I, Context<'i, I>, State, TokenKind>
for PgParser<'i, I, L, B>
where
    I: InputT + ?Sized + Debug,
    L: Lexer<'i, Context<'i, I>, State, TokenKind, Input = I>,
    B: LRBuilder<'i, I, Context<'i, I>, State, ProdKind, TokenKind>,
{
    type Output = B::Output;
    fn parse(&self, input: &'i I) -> Result<Self::Output> {
        self.0.parse(input)
    }
    fn parse_with_context(
        &self,
        context: &mut Context<'i, I>,
        input: &'i I,
    ) -> Result<Self::Output> {
        self.0.parse_with_context(context, input)
    }
    fn parse_file<'a, F: AsRef<std::path::Path>>(
        &'a mut self,
        file: F,
    ) -> Result<Self::Output>
    where
        'a: 'i,
    {
        self.0.parse_file(file)
    }
}
#[allow(dead_code)]
#[derive(Debug)]
pub enum Recognizer {
    Stop,
    StrMatch(&'static str),
    RegexMatch(Lazy<Regex>),
}
#[allow(dead_code)]
#[derive(Debug)]
pub struct TokenRecognizer(TokenKind, Recognizer);
impl<'i> TokenRecognizerT<'i> for TokenRecognizer {
    fn recognize(&self, input: &'i str) -> Option<&'i str> {
        match &self {
            #[allow(unused_variables)]
            TokenRecognizer(token_kind, Recognizer::StrMatch(s)) => {
                logn!("{} {:?} -- ", "    Recognizing".green(), token_kind);
                if input.starts_with(s) {
                    log!("{}", "recognized".bold().green());
                    Some(s)
                } else {
                    log!("{}", "not recognized".red());
                    None
                }
            }
            #[allow(unused_variables)]
            TokenRecognizer(token_kind, Recognizer::RegexMatch(r)) => {
                logn!("{} {:?} -- ", "    Recognizing".green(), token_kind);
                let match_str = r.find(input);
                match match_str {
                    Some(x) => {
                        let x_str = x.as_str();
                        log!("{} '{}'", "recognized".bold().green(), x_str);
                        Some(x_str)
                    }
                    _ => {
                        log!("{}", "not recognized".red());
                        None
                    }
                }
            }
            TokenRecognizer(_, Recognizer::Stop) => {
                logn!("{} STOP -- ", "    Recognizing".green());
                if input.is_empty() {
                    log!("{}", "recognized".bold().green());
                    Some("")
                } else {
                    log!("{}", "not recognized".red());
                    None
                }
            }
        }
    }
}
pub(crate) static RECOGNIZERS: [TokenRecognizer; TERMINAL_COUNT] = [
    TokenRecognizer(TokenKind::STOP, Recognizer::Stop),
    TokenRecognizer(
        TokenKind::UNQUOTED_STRING,
        Recognizer::RegexMatch(
            Lazy::new(|| { Regex::new(concat!("^", "\"((\\\\\")|[^\"])*\"")).unwrap() }),
        ),
    ),
    TokenRecognizer(
        TokenKind::IDENTIFIER,
        Recognizer::RegexMatch(
            Lazy::new(|| { Regex::new(concat!("^", "\\w+")).unwrap() }),
        ),
    ),
    TokenRecognizer(TokenKind::SEMICOLON, Recognizer::StrMatch(";")),
    TokenRecognizer(TokenKind::CREATE, Recognizer::StrMatch("CREATE")),
    TokenRecognizer(TokenKind::NODE, Recognizer::StrMatch("NODE")),
    TokenRecognizer(TokenKind::EDGE, Recognizer::StrMatch("EDGE")),
    TokenRecognizer(TokenKind::GRAPH, Recognizer::StrMatch("GRAPH")),
    TokenRecognizer(TokenKind::TYPE, Recognizer::StrMatch("TYPE")),
    TokenRecognizer(TokenKind::OPEN_PAREN, Recognizer::StrMatch("(")),
    TokenRecognizer(TokenKind::CLOSE_PAREN, Recognizer::StrMatch(")")),
    TokenRecognizer(TokenKind::OPEN_ARROW, Recognizer::StrMatch("-[")),
    TokenRecognizer(TokenKind::CLOSE_ARROW, Recognizer::StrMatch("]->")),
    TokenRecognizer(TokenKind::OPEN_CURLY, Recognizer::StrMatch("{")),
    TokenRecognizer(TokenKind::CLOSE_CURLY, Recognizer::StrMatch("}")),
    TokenRecognizer(TokenKind::COLON, Recognizer::StrMatch(":")),
    TokenRecognizer(TokenKind::COMMA, Recognizer::StrMatch(",")),
    TokenRecognizer(TokenKind::BAR, Recognizer::StrMatch("|")),
    TokenRecognizer(TokenKind::PLUS, Recognizer::StrMatch("+")),
    TokenRecognizer(TokenKind::STAR, Recognizer::StrMatch("*")),
    TokenRecognizer(TokenKind::QUESTION, Recognizer::StrMatch("?")),
    TokenRecognizer(TokenKind::INTEGER_NAME, Recognizer::StrMatch("INTEGER")),
    TokenRecognizer(TokenKind::STRING_NAME, Recognizer::StrMatch("STRING")),
    TokenRecognizer(TokenKind::DATE_NAME, Recognizer::StrMatch("DATE")),
    TokenRecognizer(
        TokenKind::NUMBER,
        Recognizer::RegexMatch(
            Lazy::new(|| { Regex::new(concat!("^", "\\d+")).unwrap() }),
        ),
    ),
    TokenRecognizer(TokenKind::OPTIONAL, Recognizer::StrMatch("OPTIONAL")),
    TokenRecognizer(TokenKind::QUOTE, Recognizer::StrMatch("\\\"")),
];
pub struct DefaultBuilder {
    res_stack: Vec<Symbol>,
}
impl DefaultBuilder {
    #[allow(dead_code)]
    pub fn new() -> Self {
        Self { res_stack: vec![] }
    }
}
impl Builder for DefaultBuilder {
    type Output = pg_actions::Pg;
    fn get_result(&mut self) -> Self::Output {
        match self.res_stack.pop().unwrap() {
            Symbol::NonTerminal(NonTerminal::Pg(r)) => r,
            _ => panic!("Invalid result on the parse stack!"),
        }
    }
}
impl<'i> LRBuilder<'i, Input, Context<'i, Input>, State, ProdKind, TokenKind>
for DefaultBuilder {
    #![allow(unused_variables)]
    fn shift_action(
        &mut self,
        context: &Context<'i, Input>,
        token: Token<'i, Input, TokenKind>,
    ) {
        let val = match token.kind {
            TokenKind::STOP => panic!("Cannot shift STOP token!"),
            TokenKind::UNQUOTED_STRING => {
                Terminal::UNQUOTED_STRING(pg_actions::unquoted_string(context, token))
            }
            TokenKind::IDENTIFIER => {
                Terminal::IDENTIFIER(pg_actions::identifier(context, token))
            }
            TokenKind::OPEN_PAREN => Terminal::OPEN_PAREN,
            TokenKind::CLOSE_PAREN => Terminal::CLOSE_PAREN,
            TokenKind::OPEN_CURLY => Terminal::OPEN_CURLY,
            TokenKind::CLOSE_CURLY => Terminal::CLOSE_CURLY,
            TokenKind::COLON => Terminal::COLON,
            TokenKind::COMMA => Terminal::COMMA,
            TokenKind::NUMBER => Terminal::NUMBER(pg_actions::number(context, token)),
            TokenKind::QUOTE => Terminal::QUOTE,
            _ => panic!("Shift of unreachable terminal!"),
        };
        self.res_stack.push(Symbol::Terminal(val));
    }
    fn reduce_action(
        &mut self,
        context: &Context<'i, Input>,
        prod: ProdKind,
        prod_len: usize,
    ) {
        let prod = match prod {
            ProdKind::PgP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::Nodes(p0)) => {
                        NonTerminal::Pg(pg_actions::pg_nodes(context, p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::NodesEachOf => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 3usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap(), i.next().unwrap()) {
                    (
                        Symbol::NonTerminal(NonTerminal::Nodes(p0)),
                        _,
                        Symbol::NonTerminal(NonTerminal::Nodes(p1)),
                    ) => NonTerminal::Nodes(pg_actions::nodes_each_of(context, p0, p1)),
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::NodesSingleNode => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::Node(p0)) => {
                        NonTerminal::Nodes(pg_actions::nodes_single_node(context, p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::NodeP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 4usize)
                    .into_iter();
                match (
                    i.next().unwrap(),
                    i.next().unwrap(),
                    i.next().unwrap(),
                    i.next().unwrap(),
                ) {
                    (
                        _,
                        Symbol::NonTerminal(NonTerminal::Id(p0)),
                        Symbol::NonTerminal(NonTerminal::LabelPropertySpec(p1)),
                        _,
                    ) => NonTerminal::Node(pg_actions::node_c1(context, p0, p1)),
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::IdP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::Terminal(Terminal::IDENTIFIER(p0)) => {
                        NonTerminal::Id(pg_actions::id_identifier(context, p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::LabelPropertySpecP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 2usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap()) {
                    (
                        Symbol::NonTerminal(NonTerminal::LabelSpecOpt(p0)),
                        Symbol::NonTerminal(NonTerminal::PropertySpecOpt(p1)),
                    ) => {
                        NonTerminal::LabelPropertySpec(
                            pg_actions::label_property_spec_c1(context, p0, p1),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::LabelSpecOptP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::LabelSpec(p0)) => {
                        NonTerminal::LabelSpecOpt(
                            pg_actions::label_spec_opt_label_spec(context, p0),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::LabelSpecOptP2 => {
                NonTerminal::LabelSpecOpt(pg_actions::label_spec_opt_empty(context))
            }
            ProdKind::PropertySpecOptP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::PropertySpec(p0)) => {
                        NonTerminal::PropertySpecOpt(
                            pg_actions::property_spec_opt_property_spec(context, p0),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::PropertySpecOptP2 => {
                NonTerminal::PropertySpecOpt(
                    pg_actions::property_spec_opt_empty(context),
                )
            }
            ProdKind::LabelSpecP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 2usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap()) {
                    (_, Symbol::Terminal(Terminal::IDENTIFIER(p0))) => {
                        NonTerminal::LabelSpec(
                            pg_actions::label_spec_identifier(context, p0),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::PropertySpecP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 3usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap(), i.next().unwrap()) {
                    (_, Symbol::NonTerminal(NonTerminal::Properties(p0)), _) => {
                        NonTerminal::PropertySpec(
                            pg_actions::property_spec_properties(context, p0),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::PropertiesEachOfProperties => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 3usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap(), i.next().unwrap()) {
                    (
                        Symbol::NonTerminal(NonTerminal::Properties(p0)),
                        _,
                        Symbol::NonTerminal(NonTerminal::Properties(p1)),
                    ) => {
                        NonTerminal::Properties(
                            pg_actions::properties_each_of_properties(context, p0, p1),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::PropertiesBaseProperty => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::Property(p0)) => {
                        NonTerminal::Properties(
                            pg_actions::properties_base_property(context, p0),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::PropertyP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 3usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap(), i.next().unwrap()) {
                    (
                        Symbol::NonTerminal(NonTerminal::key(p0)),
                        _,
                        Symbol::NonTerminal(NonTerminal::Values(p1)),
                    ) => NonTerminal::Property(pg_actions::property_c1(context, p0, p1)),
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::keyP1 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::Terminal(Terminal::IDENTIFIER(p0)) => {
                        NonTerminal::key(pg_actions::key_identifier(context, p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::ValuesEachOfValues => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 3usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap(), i.next().unwrap()) {
                    (
                        Symbol::NonTerminal(NonTerminal::Values(p0)),
                        _,
                        Symbol::NonTerminal(NonTerminal::Values(p1)),
                    ) => {
                        NonTerminal::Values(
                            pg_actions::values_each_of_values(context, p0, p1),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::ValuesP2 => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::NonTerminal(NonTerminal::SingleValue(p0)) => {
                        NonTerminal::Values(pg_actions::values_single_value(context, p0))
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::SingleValueStringValue => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 3usize)
                    .into_iter();
                match (i.next().unwrap(), i.next().unwrap(), i.next().unwrap()) {
                    (_, Symbol::Terminal(Terminal::UNQUOTED_STRING(p0)), _) => {
                        NonTerminal::SingleValue(
                            pg_actions::single_value_string_value(context, p0),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
            ProdKind::SingleValueNumberValue => {
                let mut i = self
                    .res_stack
                    .split_off(self.res_stack.len() - 1usize)
                    .into_iter();
                match i.next().unwrap() {
                    Symbol::Terminal(Terminal::NUMBER(p0)) => {
                        NonTerminal::SingleValue(
                            pg_actions::single_value_number_value(context, p0),
                        )
                    }
                    _ => panic!("Invalid symbol parse stack data."),
                }
            }
        };
        self.res_stack.push(Symbol::NonTerminal(prod));
    }
}
